/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as remicoPaySol from "./RemicoPay.sol";
export { MockHKDR__factory } from "./MockHKDR__factory";
export { MockPHPC__factory } from "./MockPHPC__factory";
