/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMockPHPC,
  IMockPHPCInterface,
} from "../../../contracts/RemicoPay.sol/IMockPHPC";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMockPHPC__factory {
  static readonly abi = _abi;
  static createInterface(): IMockPHPCInterface {
    return new Interface(_abi) as IMockPHPCInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMockPHPC {
    return new Contract(address, _abi, runner) as unknown as IMockPHPC;
  }
}
