/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMockPHPC__factory } from "./IMockPHPC__factory";
export { RemicoPay__factory } from "./RemicoPay__factory";
