/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as remicoPaySol from "./RemicoPay.sol";
export type { remicoPaySol };
export type { MockHKDR } from "./MockHKDR";
export type { MockPHPC } from "./MockPHPC";
