/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RemicoPay {
  export type RemittanceStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    hkdAmount: BigNumberish;
    phpAmount: BigNumberish;
    fee: BigNumberish;
    lockedRate: BigNumberish;
    createdAt: BigNumberish;
    status: BigNumberish;
  };

  export type RemittanceStructOutput = [
    sender: string,
    recipient: string,
    hkdAmount: bigint,
    phpAmount: bigint,
    fee: bigint,
    lockedRate: bigint,
    createdAt: bigint,
    status: bigint
  ] & {
    sender: string;
    recipient: string;
    hkdAmount: bigint;
    phpAmount: bigint;
    fee: bigint;
    lockedRate: bigint;
    createdAt: bigint;
    status: bigint;
  };
}

export interface RemicoPayInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeRemittance"
      | "createRemittance"
      | "exchangeRate"
      | "feeBps"
      | "getQuote"
      | "getRemittance"
      | "hkdr"
      | "nextRemitId"
      | "owner"
      | "phpc"
      | "refundRemittance"
      | "remittances"
      | "renounceOwnership"
      | "setExchangeRate"
      | "setFeeBps"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExchangeRateUpdated"
      | "FeeBpsUpdated"
      | "OwnershipTransferred"
      | "RemittanceCompleted"
      | "RemittanceCreated"
      | "RemittanceRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeRemittance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRemittance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeRate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemittance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hkdr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextRemitId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "phpc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundRemittance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "remittances",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExchangeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "completeRemittance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRemittance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getQuote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRemittance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hkdr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextRemitId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "phpc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundRemittance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remittances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ExchangeRateUpdatedEvent {
  export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
  export type OutputTuple = [oldRate: bigint, newRate: bigint];
  export interface OutputObject {
    oldRate: bigint;
    newRate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeBpsUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceCompletedEvent {
  export type InputTuple = [
    remitId: BigNumberish,
    recipient: AddressLike,
    phpAmount: BigNumberish
  ];
  export type OutputTuple = [
    remitId: bigint,
    recipient: string,
    phpAmount: bigint
  ];
  export interface OutputObject {
    remitId: bigint;
    recipient: string;
    phpAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceCreatedEvent {
  export type InputTuple = [
    remitId: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    hkdAmount: BigNumberish,
    phpAmount: BigNumberish,
    fee: BigNumberish,
    rate: BigNumberish
  ];
  export type OutputTuple = [
    remitId: bigint,
    sender: string,
    recipient: string,
    hkdAmount: bigint,
    phpAmount: bigint,
    fee: bigint,
    rate: bigint
  ];
  export interface OutputObject {
    remitId: bigint;
    sender: string;
    recipient: string;
    hkdAmount: bigint;
    phpAmount: bigint;
    fee: bigint;
    rate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemittanceRefundedEvent {
  export type InputTuple = [
    remitId: BigNumberish,
    sender: AddressLike,
    hkdAmount: BigNumberish
  ];
  export type OutputTuple = [
    remitId: bigint,
    sender: string,
    hkdAmount: bigint
  ];
  export interface OutputObject {
    remitId: bigint;
    sender: string;
    hkdAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RemicoPay extends BaseContract {
  connect(runner?: ContractRunner | null): RemicoPay;
  waitForDeployment(): Promise<this>;

  interface: RemicoPayInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeRemittance: TypedContractMethod<
    [remitId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createRemittance: TypedContractMethod<
    [recipient: AddressLike, hkdAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  exchangeRate: TypedContractMethod<[], [bigint], "view">;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  getQuote: TypedContractMethod<
    [hkdAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        phpAmount: bigint;
        fee: bigint;
        rate: bigint;
      }
    ],
    "view"
  >;

  getRemittance: TypedContractMethod<
    [remitId: BigNumberish],
    [RemicoPay.RemittanceStructOutput],
    "view"
  >;

  hkdr: TypedContractMethod<[], [string], "view">;

  nextRemitId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  phpc: TypedContractMethod<[], [string], "view">;

  refundRemittance: TypedContractMethod<
    [remitId: BigNumberish],
    [void],
    "nonpayable"
  >;

  remittances: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        sender: string;
        recipient: string;
        hkdAmount: bigint;
        phpAmount: bigint;
        fee: bigint;
        lockedRate: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setExchangeRate: TypedContractMethod<
    [newRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeBps: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeRemittance"
  ): TypedContractMethod<[remitId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createRemittance"
  ): TypedContractMethod<
    [recipient: AddressLike, hkdAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exchangeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuote"
  ): TypedContractMethod<
    [hkdAmount: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        phpAmount: bigint;
        fee: bigint;
        rate: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRemittance"
  ): TypedContractMethod<
    [remitId: BigNumberish],
    [RemicoPay.RemittanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hkdr"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextRemitId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "phpc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundRemittance"
  ): TypedContractMethod<[remitId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remittances"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        sender: string;
        recipient: string;
        hkdAmount: bigint;
        phpAmount: bigint;
        fee: bigint;
        lockedRate: bigint;
        createdAt: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExchangeRate"
  ): TypedContractMethod<[newRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeBps"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExchangeRateUpdated"
  ): TypedContractEvent<
    ExchangeRateUpdatedEvent.InputTuple,
    ExchangeRateUpdatedEvent.OutputTuple,
    ExchangeRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeBpsUpdated"
  ): TypedContractEvent<
    FeeBpsUpdatedEvent.InputTuple,
    FeeBpsUpdatedEvent.OutputTuple,
    FeeBpsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceCompleted"
  ): TypedContractEvent<
    RemittanceCompletedEvent.InputTuple,
    RemittanceCompletedEvent.OutputTuple,
    RemittanceCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceCreated"
  ): TypedContractEvent<
    RemittanceCreatedEvent.InputTuple,
    RemittanceCreatedEvent.OutputTuple,
    RemittanceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RemittanceRefunded"
  ): TypedContractEvent<
    RemittanceRefundedEvent.InputTuple,
    RemittanceRefundedEvent.OutputTuple,
    RemittanceRefundedEvent.OutputObject
  >;

  filters: {
    "ExchangeRateUpdated(uint256,uint256)": TypedContractEvent<
      ExchangeRateUpdatedEvent.InputTuple,
      ExchangeRateUpdatedEvent.OutputTuple,
      ExchangeRateUpdatedEvent.OutputObject
    >;
    ExchangeRateUpdated: TypedContractEvent<
      ExchangeRateUpdatedEvent.InputTuple,
      ExchangeRateUpdatedEvent.OutputTuple,
      ExchangeRateUpdatedEvent.OutputObject
    >;

    "FeeBpsUpdated(uint256,uint256)": TypedContractEvent<
      FeeBpsUpdatedEvent.InputTuple,
      FeeBpsUpdatedEvent.OutputTuple,
      FeeBpsUpdatedEvent.OutputObject
    >;
    FeeBpsUpdated: TypedContractEvent<
      FeeBpsUpdatedEvent.InputTuple,
      FeeBpsUpdatedEvent.OutputTuple,
      FeeBpsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RemittanceCompleted(uint256,address,uint256)": TypedContractEvent<
      RemittanceCompletedEvent.InputTuple,
      RemittanceCompletedEvent.OutputTuple,
      RemittanceCompletedEvent.OutputObject
    >;
    RemittanceCompleted: TypedContractEvent<
      RemittanceCompletedEvent.InputTuple,
      RemittanceCompletedEvent.OutputTuple,
      RemittanceCompletedEvent.OutputObject
    >;

    "RemittanceCreated(uint256,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RemittanceCreatedEvent.InputTuple,
      RemittanceCreatedEvent.OutputTuple,
      RemittanceCreatedEvent.OutputObject
    >;
    RemittanceCreated: TypedContractEvent<
      RemittanceCreatedEvent.InputTuple,
      RemittanceCreatedEvent.OutputTuple,
      RemittanceCreatedEvent.OutputObject
    >;

    "RemittanceRefunded(uint256,address,uint256)": TypedContractEvent<
      RemittanceRefundedEvent.InputTuple,
      RemittanceRefundedEvent.OutputTuple,
      RemittanceRefundedEvent.OutputObject
    >;
    RemittanceRefunded: TypedContractEvent<
      RemittanceRefundedEvent.InputTuple,
      RemittanceRefundedEvent.OutputTuple,
      RemittanceRefundedEvent.OutputObject
    >;
  };
}
